### ISSUE TITLE
react-script.phtml uses var over let or const and deprecated escapeUrl method

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#104]
The react-script.phtml file under `view/frontend/templates` still uses `var` keyword over the much more common and sensible `let` and `const`. Nowadays 99.67% of users have a browser compatible according to `caniuse.com/const`. What kind of browser support is this repo aiming for? Can we switch to using const?

other than that a deprecated method `$block->escapeUrl` from magento is used here, this should just be replaced with an `$escaper` I think.
> 103.0.0 Use $escaper directly in templates and in blocks.

**Comment by progammer-rkt** [comment]
You are totally right on the `$block->escapeUrl` usage. Instead of that, we should rely on `$escaper`.

However, it would be better to rely on `var` on variable declarations as the browsers still consider to be supported up to ES5. The support for ES6 is in "progress" in terms of browsers.

**Comment by progammer-rkt** [comment]
The improvement suggested is integrated and reached `develop` now. Hence, closing this issue.
