### ISSUE TITLE
Clicking shipping or payment method options in quick succession bounces them back and forth

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#107]
Currently when you click a shipping or payment method and adjust your choice before the corresponding graphql call finishes it bounces back to the choice from before the graphql call. 

This seems to be the flow of operations;  

Pick option 1 > async GQL to backend 1 happens > pick option 2 > async GQL to backend 2 happens > async GQL results 1 come in > page renders option 1 as picked > async GQL results 2 come in > page renders option 2 as picked

**Comment by progammer-rkt** [comment]
I think showing the loader would avoid this situation.

**Comment by progammer-rkt** [comment]
Loader is again available in the development mode. I really hope that will avoid this issue. Hence, closing this.
