### ISSUE TITLE
Usage of deprecated KeyboardEvent.keyCode

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#112]
also see: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

In two occassions the old and deprecated KeyboardEvent.keyCode syntax is being used.

reactapp/src/hook/useEnterActionInForm.js
```javascript
  return event => {
    if (event.keyCode !== 13) {
      return;
    }
```

reactapp/src/components/checkoutAgreements/components/CheckoutAgreementModalWrapper.jsx
```javascript
    // Event handler that closes the modal on pressing `ESC` in keyboard.
    const keyDownHandler = event => {
      if (event.keyCode === 27) {
        setActiveModalId(false);
      }
    };
```

I suggest replacing these and using only [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) or [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key). This simplifies code and removes the need for comments too.

**Comment by progammer-rkt** [comment]
@peterschriever Thank you. I didn't know `event.keyCode` is outdated. Well noted and the PR you can find here: #135
