### ISSUE TITLE
Why is lodash.get (_get) being used when optional object chaining can be

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#114]
Why is the lodash.get aka `_get(object, key)` being used so much throughout the codebase when practically all usage of it can be replaced by the [optional chaining operator (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

ex:
```javascript
  const formSectionErrors = _get(errors, formSectionId);

  const formSectionErrors = errors?.[formSectionId];

  const formSectionErrors = errors?.[formSectionId] ?? 'defaultValue';
```

I understand theres some heavy lodash requirements in `Yup` which is in turn tightly coupled with `formik` but theres no reason to use this function in our own code in my opinion

**Comment by progammer-rkt** [comment]
@peterschriever There is no reason other than that is my personal preference.

Optional changing operator is new to modern javascript (ECMA 2020) I believe. Before that, `lodash.get` is what I used widely to avoid unwanted errors while doing deep chaining. I have no problem with getting rid of `lodash.get` in a future version for sure.
