### ISSUE TITLE
Selecting Payment Method for the first time is not updated properly in formik

### ISSUE THREAD

**Issue by jladmore** [hyva-themes/magento2-hyva-checkout#119]
When you launch checkout for the first time and quickly enter, e-mail, shipping address and shipping method and then select a payment method, fill in the details and then place order. The error comes back

Payment Method is not registered or something like this. 

The problem is when we setFieldValue in the components/PaymentMethodList.jsx there is a race condition wityh the next call to setFieldTouched

placing an await in front of the setfieldValue call resolves the issue.

**Comment by progammer-rkt** [comment]
The PR is merged and hence closing the issue. Thanks for the contribution @jladmore
