### ISSUE TITLE
lockfile not in sync with package.json

### ISSUE THREAD

**Issue by DanielRuf** [hyva-themes/magento2-hyva-checkout#125]
`npm ci` is needed for consistent deployments

Currently it seems the lockfile was not udpated for a while.
Running `npm ci` leads to `cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
`
https://github.com/hyva-themes/magento2-hyva-checkout/tree/develop/src/reactapp

So please don't forget to update the lockfile =)

**Comment by progammer-rkt** [comment]
@DanielRuf Thanks for reporting the issue. There is #130 with which all packages will be updated to the latest versions and also the package-lock.json too.

**Comment by DanielRuf** [comment]
Awesome, thank you very much =)
