### ISSUE TITLE
Wrong dispatch sent to API methods

### ISSUE THREAD

**Issue by jladmore** [hyva-themes/magento2-hyva-checkout#128]
Should always be the AppDispatch but the CartDispatch is being used in some of the calls. This causes problems when trying to report errors in the checkout. Both dispatches may need to be sent to these methods as the cart dispatch is used in examples like this

```
export function setOrderInfoAction(dispatch, order) {
  dispatch({
    type: SET_ORDER_INFO,
    payload: order,
  });
}
```

**Comment by progammer-rkt** [comment]
Thank you for reporting this issue. The fix is now reached `develop` branch and hence, closing this issue.

**Comment by jladmore** [comment]
Thanks Rajeev
~jono
Crayons Retail Pty Ltd
Unit 3C/137-139 Silverwater Road
Silverwater, NSW, Australia
email: ***@***.***
phone: 1300 232 111
mob: +61 401 890 256
skype: jonathonladmore
