### ISSUE TITLE
Countries GraphQL query throws error over explode function in getStateRequiredCountries(): array

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#138]
Upon installing the latest version of the checkout into a magento 2.3.5-p2 project we encountered a bug in the `countries` GraphQL Query.

query send:
```graphql
{
  countries {
    id
  }
}
```

result:
```json
{
  "errors": [
    {
      "debugMessage": "explode() expects parameter 2 to be string, null given",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "countries"
      ]
    }
  ],
  "data": {
    "countries": null
  }
}
```

expected:
```json
{
  "data": {
    "countries": [
      {
        "id": "BE"
      },
      {
        "id": "NL"
      }
    ]
  }
}
```

The culprit appears to be within the `getStateRequiredCountries(): array` method, inside `Hyva/Checkout/Plugin/DirectoryModel/SetStateRequired.php`. Here the explode function fails and throws the error because in our project the configuration string `'general/region/state_required'` doesnt exist.

I will open up a PR adding a simple if check to test if the configuration doesnt exist and return an empty array instead of erroring out. However I also believe we should somewhere document the dependency on this configuration setting and how developers should configure it appropriately. This I shall leave up to you to decide.

**Comment by schmengler** [comment]
Thanks for the well described issue!

**Comment by progammer-rkt** [comment]
Thank you for your contribution. The fix is merged into the `develop` branch. Closing this issue
