### ISSUE TITLE
Translations popping in after components are rendered is bad UX (+BUG: translations dont apply outside of render funcs)

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#143]
Currently the checkout loads translation files asynchronously and without blocking rendering of components. This is great for performance mostly, but creates a poor user experience (ux). The texts suddenly pop in.

I would expect the checkout to hang on some loading state while fetching the language file, perhaps halting rendering of any components until it is finished.

This could be related to #118 if it results in a change of how the translation strings are fetched.

**Comment by peterschriever** [comment]
More than bad UX theres this bug because the translation files load in after the code is ran I believe. When trying to translate the Formik/Yup validation strings like this one in `ShippingAddressFormikProvider.jsx`
```js
const requiredMessage = __('%1 is required');
```

The actual result will be that it always stays English and never updates the string. A quick fix is to move the code down, into the render function.. But this is not ideal of course and I as a developer would expect these assignments are ok being constant and unchanging from render to render.

**Comment by progammer-rkt** [comment]
@peterschriever I didn't face this issue before. It will correctly translate the strings if you have the translation JSON file present. Did you check this in production mode or during `npm start`?

**Comment by peterschriever** [comment]
This happens for both `npm start` and when build in magento context for me. Also I noticed the script `move-i18n-to-static-dir` was not being called when building the checkout, its not in develop branch either. I added `"postbuild": "npm run move-i18n-to-static-dir",` now to ensure our `nl_NL` file is moved. The issue with translation strings defined outside of render functions still stands though.

**Comment by progammer-rkt** [comment]
@peterschriever We are now using a different approach for translation. The translations will be done from the template files and thus we are re-using the Magento  built-in translation facility. This will also allow us to load the translation synchronously.

So this issue does not prevail now. Hence, closing the issue.
