### ISSUE TITLE
Why is it that for the useAppContext hook all data is exposed, but in useCartContext only select values are?

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#152]
I was creating a custom component when to my surprise I found that the `useCartContext` hook behaved very much differently from the `useAppContext` hook! Why is this the case? Why are only those select values exposed from the `useCartContext` hook?

useCartContext.js
```js
import { useContext } from 'react';
import _get from 'lodash.get';

import CartContext from '../context/Cart/CartContext';

export default function useCartContext() {
  const [cartData, cartActions] = useContext(CartContext);
  const { getGuestCartInfo, placeOrder } = cartActions;
  const cart = _get(cartData, 'cart');
  const orderId = _get(cartData, 'order.order_number');
  const selectedPaymentMethod = _get(cart, 'selected_payment_method');
  const selectedShippingMethod = _get(cart, 'selected_shipping_method');
  const loaded = _get(cart, 'loaded');

  return {
    orderId,
    placeOrder,
    getGuestCartInfo,
    selectedPaymentMethod,
    selectedShippingMethod,
    loaded,
  };
}
```

useAppContext.js
```js
import { useContext } from 'react';
import AppContext from '../context/App/AppContext';

export default function useAppContext() {
  return useContext(AppContext);
}
```

In the same category, why is there no generic `useFormikContext` hook? My code now looks as follows, which I find very ugly;
```js
import { FormikContext } from 'formik';
import useAppContext from '../../../hook/useAppContext';
import CartContext from '../../../context/Cart/CartContext';

export default function useAddressStepContext() {
  const { errors, values } = useContext(FormikContext);
  const [, { setEmailOnGuestCart }] = useContext(CartContext);
  const { subscribeToNewsletter } = useAppContext();
```

**Comment by progammer-rkt** [comment]
We are now using a consistent approach for both `useAppContext` and `useCartContext`. see this: https://github.com/hyva-themes/magento2-hyva-checkout/blob/main/src/reactapp/src/hook/useCartContext.jsx

```
export default function useCartContext() {
  const [cartData, cartActions] = useContext(CartContext);

  return {
    ...cartData,
    ...cartActions,
  };
}
```

Due to this, we can access any data or action by destructuring assignment technique by referring the hook. An example,

```
const { cart, getGuestCartInfo} = useCartContext();
```

I also recommend to use this `useAppContext` and `useCartContext` in localised AppContext and CartContext.

**Comment by progammer-rkt** [comment]
@peterschriever I am closing this issue as it no longer inconsistent any more. Feel free to re-open this if you feel differently
