### ISSUE TITLE
on reload, email is loaded into checkout, but not visible

### ISSUE THREAD

**Issue by wigman** [hyva-themes/magento2-hyva-checkout#174]
The email address is hidden on reload, while the GQL cart call does show that the email address is present.

Clicking "edit" also renders an empty email field.

![image](https://user-images.githubusercontent.com/4800926/133445352-cc82fe39-58ed-4971-85c1-00e302c0cc37.png)

**Comment by progammer-rkt** [comment]
This will be probably fixed with #176
