### ISSUE TITLE
new parser setup breaks alias setup with Yireo Example Checkout

### ISSUE THREAD

**Issue by DanielRuf** [hyva-themes/magento2-hyva-checkout#181]
It seems the new parser setup breaks projects with alias configurations.

Here the new parser was added:
https://github.com/hyva-themes/magento2-hyva-checkout/commit/6320c49ef6b79320d180c1af43ed116f7163e7d6#diff-c9fbe45db4b426bcbfa0b209c78e49d625b109e2c473263f232fd756dde5fe77R74

And here it was loaded in the eslint config:
https://github.com/hyva-themes/magento2-hyva-checkout/commit/777548bbc882d967a04e85a3ed9ea9982b76a0df

We had to temporarily add `'import/no-unresolved': 0,` to the eslint config to make eslint happy and get everything to build.

Related:
https://github.com/babel/babel/issues/11975 (happens when setting the alias via eslintrc config for the import plugin)

Also scoped (`@hyva/...`) aliases won't work anymore due to this: https://github.com/import-js/eslint-plugin-import/blob/9bac44e629105572ca78a532c968df202e5a18b8/src/core/importType.js#L46

https://github.com/import-js/eslint-plugin-import/issues/496
https://github.com/tleunen/eslint-import-resolver-babel-module/issues/77 (related to `@` aliases)
https://github.com/aze3ma/react-app-rewire-aliases/issues/1 ( issue starts at the react-app-rewired level)

https://github.com/yireo-training/Yireo_ExampleHyvaCheckout/blob/master/reactapp/config-overrides.js#L53 (the current setup)

**Comment by progammer-rkt** [comment]
@DanielRuf I checked out `Yireo_ExampleHyvaCheckout` module and fixed the incompatibility with the `1.0.00rc2`. You can find the PR here: https://github.com/yireo-training/Yireo_ExampleHyvaCheckout/pull/2

**Comment by progammer-rkt** [comment]
@DanielRuf We have a new space for this: https://github.com/hyva-themes/magento2-checkout-example

So we will be focusing on this repo from now onwards.
