### ISSUE TITLE
Can't checkout when only virtual items in cart

### ISSUE THREAD

**Issue by nfourteen** [hyva-themes/magento2-hyva-checkout#186]
Hyva Checkout v1.0.0-rc
With only virtual items in the cart, shipping info is required and prevents checkout.

<img width="1680" alt="Screen Shot 2021-09-25 at 3 45 12 PM" src="https://user-images.githubusercontent.com/14304240/134785126-21e431fa-18b8-42a9-89ec-94566d298b5d.png">

**Comment by progammer-rkt** [comment]
This is now available in `1.0.0-rc` and soon will be available in the stable release `1.0.0`
