### ISSUE TITLE
Consider using preact instead?

### ISSUE THREAD

**Issue by jahvi** [hyva-themes/magento2-hyva-checkout#2]
I was wondering if you had considered using preact instead of React? It follows a similar concept to tailwind and alpine in that it tries to keep the codebase lightweight while providing virtually the same API as React, so it thought it could align better with the project vision.

I ran some test locally and switching to preact cuts the final `react-checkout.js` bundle by over **35%** (92kb to 60kb) without any loss in functionality or having to refactor a single file.

Do you think there could be downsides to this?

**Comment by wigman** [comment]
I’m all for it! It was on the roadmap to try as soon as the general structure was done (lots of refactoring to do!) but now is not a bad time!
Feel free to PR, otherwise it will be done sometime later :)

**Comment by jahvi** [comment]
Sure thing, I just submitted a PR.

I included the bundled files as well but not sure how you want to handle those.

**Comment by wigman** [comment]
Added with #3 and merged with #5.
Many thanks, @jahvi !

**Comment by jahvi** [comment]
No worries, you can use the same approach for Formik and something like react-final-form and get similar results but that will require more work.

If you think it's worth it I can have a look into it.
