### ISSUE TITLE
Resolve Inconsistencies in React States While Customer Login

### ISSUE THREAD

**Issue by progammer-rkt** [hyva-themes/magento2-hyva-checkout#21]
Currently, when customer login from the checkout page itself, there occurs some react state inconsistencies. The checkout form stays in guest checkout mode.

**Comment by jladmore** [comment]
I have tried a few things and currently solved this by doing the following

in react-container.phtml

$viewModel = $block->getViewModel();
$isLoggedIn = $viewModel->customerLoggedIn();
$customerIsLoggedIn = "false";
if ($isLoggedIn) {
    $customerIsLoggedIn = "true";
}

?>
<div id="react-checkout" isLoggedIn="<?= $customerIsLoggedIn; ?>">
</div>

and in reactapp/src/context/App/initialState.js

  isLoggedIn: document.getElementById('react-checkout').getAttribute('isloggedin'),

This makes sure that this is set correctly when the app launches.

**Comment by progammer-rkt** [comment]
Hi @jladmore, thanks for your inputs. Really appreciate it.

This issue is all about the inconsistencies facing in the checkout page when the user tries to log in from the checkout page itself. Not before reaching the checkout page.

On the checkout page, it will check for the customer token in the local storage `mage-cache-storage.customer.signin_token`. If it exists, then it will treat the checkout as logged-in checkout. Else, it will be a guest checkout.

So if you set the customer token at `mage-cache-storage.customer.signin_token`, when the user login from the site, then hyva checkout will work as expected.

Let me know whether this is working for you or not.

**Comment by jladmore** [comment]
There are two issues I see in using the signin_token
1. There could be case where its defined in the mage-cache-storage, but its not valid. I have seen this in my testing, but this could be due to me having other things going on.
2. You still need to grab the token and then set the initialState of isLoggedIn to be true. When I was testing if you didn't do this in initialState.js then there could be 1-2 renders where isLoggedIn is false, due to the time it takes to set the variable

This is why I decided to Nail up the initialState of isLoggedIn to be true based on the server render.... you still use the token anyway for all GraphQL queries from this point on.

**Comment by progammer-rkt** [comment]
@jladmore Yes,  your observations are correct. I am adding my 2 cents here on this:

When a customer logged in (not from the checkout page) and has a token is stored at `mage-cache-storage.customer.signin_token`, then there is a valid session and valid token for the customer. I assume the session is by default one hour lifetime. After one hour, it will get expired. This means both the token and the session will be invalidated after one hour.

If the above hypothesis is true, then you find the token is invalid when you come to the checkout page, then the hyva-checkout will be rendered but, it will be empty. This is because the cartId stored at ``mage-cache-storage.cart.cartId` is now invalid since it is the cart id of the user who logged-in before. Since the token got expired, the cartId is not valid anymore.

So at this time, the safe bet is customer login from the checkout page or login from the site and comes to the checkout page. In both cases, it will update the customer token and with a valid customer token the cartId against the customer is again valid and it will provide the cart data through the graphql query.

**Comment by progammer-rkt** [comment]
This issue with the state inconsistencies occurring while login from the checkout page is resolved with pull request #30 

Hence closing the issue
