### ISSUE TITLE
Wrong translation on billing information

### ISSUE THREAD

**Issue by integer-tom** [hyva-themes/magento2-hyva-checkout#227]
The title of the billing information is wrongly translated in the German version. Currently it ready "Bestellübersicht" but it should be "Rechnungsadresse".
![image](https://user-images.githubusercontent.com/94903500/143014469-986e64a0-c826-4757-8629-8238921b9128.png)

**Comment by rajeev-k-tomy** [comment]
@integer-tom  The arrow points to actually to the billing address. So probably the message is wrong. However, Google says the message is also right. Can you give me the right message if the message is wrong?
![Screenshot 2021-11-29 at 12 35 32 PM](https://user-images.githubusercontent.com/7589113/143822962-b18690e0-2f1c-45a5-8545-f70d1933103a.png)
g?

**Comment by integer-tom** [comment]
Hi @rajeev-k-tomy,
"Diese Adresse als meine Rechnungsadresse verwenden" is right. But the error here is only "Bestellübersicht". It should be "Rechnungsadresse". (I marked the first one in order to show how to get to the other one.)

**Comment by rajeev-k-tomy** [comment]
The title of the billing address form section is "Billing Information".  This is actually translated by the language package into "Bestellübersicht" unfortunately. So we need to find an alternative solution here.

**Comment by schmengler** [comment]
Language pack translations override module translations, but can be overridden by theme translations. We can only recommend to fix the wrong translation in your theme if you use this language pack
