### ISSUE TITLE
VAT field missing

### ISSUE THREAD

**Issue by galanis-a** [hyva-themes/magento2-hyva-checkout#232]
version 1.0.00rc3

VAT field is missing from the address forms.

This should follow the settings in admin to show/hide vat field. 

Also it would be nice if the field is auto-filled for the logged in customer in the add address form

**Comment by rajeev-k-tomy** [comment]
@galanis-a Thank you for reporting this issue.

Hyvä Checkout does not respect customer address settings in the backend at the moment. The fields and their validations are defined at the code level and they are supposed to be changed in the code level to customize it. 

Maybe in a later version, we consider the compatibility with the address settings in the backend. But, no plans at the moment.
