### ISSUE TITLE
Checkout address extension attributes

### ISSUE THREAD

**Issue by galanis-a** [hyva-themes/magento2-hyva-checkout#233]
Extension attributes for checkout address are missing for the mutations to set the billing and shipping address.

This is useful for devs that have merchants that want more info in the addresses.

This could be a Magento 2 core graphql issue because I don't see support for this in the Magento 2 core graphql schema.

**Comment by rajeev-k-tomy** [comment]
@galanis-a Thank you for reporting this issue. 

If graphql is not allowing you to update extension attribute, then on such occasions, you should go for REST API where extension attributes are supported. You can see an example for this for payment methods update where Hyvä Checkout uses REST API methods.

Hyvä Checkout is a base where you can build your own custom checkout solution. So it should not be treated as a drop-in replacement for Luma checkout. If you need to include extension attributes, then you should build it custom at the moment.

**Comment by galanis-a** [comment]
Yeah I though so too @rajeev-k-tomy. Thank you for the REST tip!
