### ISSUE TITLE
When customer logged in .. shipping methods disappear

### ISSUE THREAD

**Issue by jladmore** [hyva-themes/magento2-hyva-checkout#27]
This is related to the array index given to the cart shipping address.... address_1

When a customer is logged in the selectedAddressId is the index from the customer address list array which will be an integer so when we do this in cart context

    const selectedShippingMethods = _get(
      cartShippingMethods,
      selectedShippingAddressId,
      []
    );

it returns blank. 

my first thought here is that this is only an issue when we have multiple shipping addresses in the cart, so we could just index this as '0' and so it will always be '0' and we are done? Who wants multiple addresses anyway..:-)

If you want multiple addresses then more work will be required to manage this!

**Comment by progammer-rkt** [comment]
@jladmore Thanks for giving this valid input. I entirely agree with you on this. we don't need unnecessary complications regarding the shipping address. So we rewrote the entire shipping address logic and it will fetch the very first shipping address entry and referring that directly.

The pull request contains this change is #30 and it is now available in the `develop` branch. It would be great if you can check this and confirm it works. We will be keeping this issue open for some time for inputs from your side and then will be closed.
