### ISSUE TITLE
Composer: Could not find a version of package hyva-themes/magento2-hyva-checkout matching your minimum-stability (alpha)

### ISSUE THREAD

**Issue by Vigneshmuthusamy** [hyva-themes/magento2-hyva-checkout#42]
I'm getting below error when I tried to install using composer.
Could not find a version of package hyva-themes/magento2-hyva-checkout matching your minimum-stability (alpha). Require it with an explicit version constraint allowing its desired stability.

**Comment by Vigneshmuthusamy** [comment]
@progammer-rkt I've executed below commands
composer config repositories.hyva-themes/magento2-hyva-checkout git git@github.com:hyva-themes/magento2-hyva-checkout.git
composer require hyva-themes/magento2-hyva-checkout

Composer require emits below issue:
Failed to update git@github.com:hyva-themes/magento2-hyva-checkout.git, package information from this repository may be outdated
                                                                                                                                               Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2

                                                                                                                                              
  [InvalidArgumentException]                                                                                                                  
  Could not find a version of package hyva-themes/magento2-hyva-checkout matching your minimum-stability (alpha). Require it with an explici  
  t version constraint allowing its desired stability.                                                                                        
                                                                                                                                              

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by progammer-rkt** [comment]
The error says you have your `minimum-stability` set to `alpha`.

Probably you may need to change it. Add below lines in your composer

```
"minimum-stability": "dev",
"prefer-stable": true,
```
Also, it is better you use the `develop` branch of the repo. The `main` branch is soon going to replace by `develop` branch and it is complete revamp of the checkout. 

For that you need to do this:

```
composer config repositories.hyva-themes/magento2-hyva-checkout git git@github.com:hyva-themes/magento2-hyva-checkout.git
composer require hyva-themes/magento2-hyva-checkout:dev-develop
```

Please remember, this repository is a tool kit. It has everything available in the repo and it will work out of the box. But in most cases, you need to customize the look and feel of it. To do that, you need a grip on React. Because of these reasons, it will be better you fork this repository and use your fork in your project.

**Comment by Vigneshmuthusamy** [comment]
ok. I tried as you recommended but I'm getting a different error now as below

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hyva-themes/magento2-hyva-checkout dev-develop requires hyva-themes/magento2-graphql-tokens dev-main -> satisfiable by hyva-themes/magento2-graphql-tokens[dev-main] but these conflict with your requirements or minimum-stability.
    - hyva-themes/magento2-hyva-checkout dev-develop requires hyva-themes/magento2-graphql-tokens dev-main -> satisfiable by hyva-themes/magento2-graphql-tokens[dev-main] but these conflict with your requirements or minimum-stability.
    - Installation request for hyva-themes/magento2-hyva-checkout dev-develop -> satisfiable by hyva-themes/magento2-hyva-checkout[dev-develop].


Installation failed, reverting ./composer.json to its original content.

**Comment by schmengler** [comment]
That sounds like you still have a minimum stability > dev. The develop branch of hyva-checkout requires the main branch of the graphql-tokens module (with updates that are not in a tagged version yet).

Explicitly requiring `dev-develop` overrides your minimum stability settings for **this** package but not for its dependencies.

So as @progammer-rkt wrote, please add this to your `composer.json`:
```
"minimum-stability": "dev",
```

if you don't want it for some reason, you have to require the graphql-token module explicitly:

```
composer require hyva-themes/magento2-hyva-checkout:dev-develop hyva-themes/magento2-graphql-tokens:dev-main
```

**Comment by progammer-rkt** [comment]
@Vigneshmuthusamy Closing this issue hoping you were able to resolve this issue in your side. Feel free to re-open this if in case you are struggling with this issue
