### ISSUE TITLE
Show discounts in checkout

### ISSUE THREAD

**Issue by schmengler** [hyva-themes/magento2-hyva-checkout#48]
~~with discount codes~~

**Comment by progammer-rkt** [comment]
We won't get discount code information from the graphql. For that, we need to customize it.

**Comment by schmengler** [comment]
OK, but can we already see the discount amount without codes?

**Comment by progammer-rkt** [comment]
@schmengler Yes, we will get the discounts. I think we can go on with that. if needed, we can integrate discount codes later.

**Comment by schmengler** [comment]
Agree. Followup ticket #65 (not part of 1.0 release)

**Comment by progammer-rkt** [comment]
Included in the pull request: #70
