### ISSUE TITLE
Facing Issue While Installing Hyva-checkout using composer

### ISSUE THREAD

**Issue by TheRealHunzik** [hyva-themes/magento2-hyva-checkout#50]
Here is My environment

Magneto 2.4.2
Php 7.4
Composer 1.10.1

Installation Steps

i have added repo in my composer.json file using

`composer config repositories.hyva-themes/magento2-hyva-checkout git git@github.com:hyva-themes/magento2-hyva-checkout.git
`

I am trying to install this package using the command

`composer require hyva-themes/magento2-hyva-checkout
`

issue i am getting is

  `Could not find a version of package hyva-themes/magento2-hyva-checkout matching your minimum-stability (alpha). Require it with an explicit version constraint allowing its desired stability.  `

please Guide

**Comment by progammer-rkt** [comment]
Hi @TheRealHunzik, please see this closed issue for more details: #42

**Comment by TheRealHunzik** [comment]
Hello @progammer-rkt , Thank you for you help i actually forget to check closed issue

Do we have a stable version of these module ?

**Comment by TheRealHunzik** [comment]
Well, that's a Great News! thank You

**Comment by progammer-rkt** [comment]
@TheRealHunzik I am closing this issue hoping you managed to resolve the issue. Feel free to open it again if in case you are still struggling with this.
