### ISSUE TITLE
Provide feedback if "place order" is not available yet

### ISSUE THREAD

**Issue by schmengler** [hyva-themes/magento2-hyva-checkout#53]
e.g. "shipping address must be filled" or "email address must be filled"

**Comment by schmengler** [comment]
Highlight inputs with invalid/missing data and focus on first field with error

**Comment by progammer-rkt** [comment]
Included in the pull request: #70

**Comment by progammer-rkt** [comment]
Test result:

> The behavior is a bit irritating: the forms are considered valid when everything is entered, regardless if "update" has been clicked. so when I enter everything but for the email address forget to click "update", I get no validation message. I think the best would be to trigger the "update" actions of all changed forms when clicking "place order". maybe in that order:
> 
> - validate
> - if valid and unsaved, trigger "update"
> - actual place order

**Comment by progammer-rkt** [comment]
Another pull request which fixes above reported issue: https://github.com/hyva-themes/magento2-hyva-checkout/pull/81
