### ISSUE TITLE
Missing CSS Styling

### ISSUE THREAD

**Issue by marcin-piechaczek** [hyva-themes/magento2-hyva-checkout#6]
This is what I ended up with:

![Screenshot 2020-10-21 at 18 32 03](https://user-images.githubusercontent.com/26635600/96750161-ebc86600-13cb-11eb-93e1-d72b1662f0a9.png)

what am I missing?

**Comment by wigman** [comment]
Hello Marcin,

I'm sorry, I have to get a base stylesheet in there. It currently expects styling to come from a generated Tailwind stylesheet that lives in the theme.
Please read my comment here: https://github.com/hyva-themes/magento2-hyva-checkout/issues/4#issuecomment-711950288

I'll add in the stylesheet soon!

**Comment by wigman** [comment]
Hi @marcin-piechaczek,

A stylesheet is now added, which you can uncomment in `src/view/frontend/layout/hyvacheckout_checkout_index.xml`

It also works in `npm start`, running the checkout headless. Please note that you have to get some Cross-origin rules in place to use `npm start`.  I'd recommend `yireo-training/magento2-corshack`

**Comment by wigman** [comment]
Also, a lot of the tailwind styling is conflicted by default Magento Luma styling if you run it in the Luma theme.
It's up to you to write the correct styling.

You can see how it's _intented_ to look like at https://hyva.io.

**Comment by adamkarnowka** [comment]
Hello - so that means that hyva-checkout won't work OOTB without hyva-themes?
I have uncommented css reference in layout xml, but file cannot be found in anywhere in the extension?

Is there any chance to install/see fully working hyva-checkout?

Thanks!

**Comment by wigman** [comment]
There's a new version on developer branch that we'll make sure will have the right styles applied in luma.

It's important to note though that this checkout is intended to be used to `build` your checkout. It's not a drop-in solution.
We'll get the new version to a state that it works out of the box with some default configuration, but customizations will require to configure and probably program a bit. We'll implement some payment methods but you'll need to activate them and compile the app.

The react checkout is currently in use on hyva.io, limburgiavlaai.nl and takeaware.nl
