### ISSUE TITLE
Unable to Checkout with Simple Product, only possible with Virtual 

### ISSUE THREAD

**Issue by TheRealHunzik** [hyva-themes/magento2-hyva-checkout#67]
I have installed Hyva CHeckout Module using composer

when I go for checkout with the simple product it gives i have installed hyva checkout and when I go to checkout I am getting `Checkout is currently only possible with Virtual Items. how to fix this anyone?` 

when I check out I found that
```
    if (cart && !cart.is_virtual) {
        return (
            <div className={'mt-2'}>
                <p class={'mt-2'}>
                    Checkout is currently only possible with Virtual Items.
                </p>
            </div>
        );
    }
```

Now it only supports virtual product checkout or I need to do some configurations?

**Comment by progammer-rkt** [comment]
@TheRealHunzik You are using the `main` branch. It supports only virtual products. You should use the `develop` branch where it supports all types of products.

**Comment by TheRealHunzik** [comment]
i am using    `"hyva-themes/magento2-hyva-checkout":""dev-main"` and this is only available using composer how i can install develop branch using composer?

**Comment by progammer-rkt** [comment]
You need to use  below commands for it:
```
composer config repositories.hyva-themes/magento2-hyva-checkout git git@github.com:hyva-themes/magento2-hyva-checkout.git
composer require hyva-themes/magento2-hyva-checkout:dev-develop
```

**Comment by progammer-rkt** [comment]
@TheRealHunzik are you still facing any issues? Can we close this thread?
