### ISSUE TITLE
PHP compatibility < 7.4

### ISSUE THREAD

**Issue by wigman** [hyva-themes/magento2-hyva-checkout#69]
Typed properties are used in https://github.com/hyva-themes/magento2-hyva-checkout/blob/develop/src/Model/LoginSectionDataService.php#L18 and https://github.com/hyva-themes/magento2-hyva-checkout/blob/develop/src/ViewModel/LocaleProvider.php#L14

These should be removed since they break on PHP versions below 7.4

**Comment by progammer-rkt** [comment]
Included in the pull request: #70
