### ISSUE TITLE
header / navigation should have same status as customer in checkout

### ISSUE THREAD

**Issue by magento-koeln** [hyva-themes/magento2-hyva-checkout#71]
Log in to customer account in hyvä checkout.

After that the problem is that in the header overlay / navigation (depends on project layout) for customer still "login" is shown and it should be "logout".

**Comment by schmengler** [comment]
An alternative solution can be to remove the header in checkout like it is done in the Luma checkout.

@wigman let's discuss it first. It may also be a simple event dispatch to update Hyvä Themes sections

**Comment by schmengler** [comment]
We can count it as resolved then
