### ISSUE TITLE
after login in hyvä checkout "edit" button of email address should disappear

### ISSUE THREAD

**Issue by magento-koeln** [hyva-themes/magento2-hyva-checkout#72]
log in in hyvä checkout with existing customer account.

When clicking in hyvä checkout on button "bearbeiten" after I logged in there is still the message "Ich melde mich and und checke aus". This is confusing because the customer is already logged in. He should get the option logout / order as guest or we should totally skip the button "bearbeiten" after successful login

![Screenshot 2021-06-10 at 21 20 04](https://user-images.githubusercontent.com/31746370/121584492-cc04b180-ca31-11eb-8eba-ed32a7ecee39.png)
![Screenshot 2021-06-10 at 21 20 09](https://user-images.githubusercontent.com/31746370/121584503-ce670b80-ca31-11eb-8010-81159b741efb.png)

**Comment by progammer-rkt** [comment]
Included in the pull request: https://github.com/hyva-themes/magento2-hyva-checkout/pull/70
