### ISSUE TITLE
edit of existing address in checkout not possible

### ISSUE THREAD

**Issue by magento-koeln** [hyva-themes/magento2-hyva-checkout#73]
Log in with existing customer account in hyvä checkout.

If you are logged in in hyvä checkout the addresses are loaded.

You need more than 2 addresses stored in your customer account (if not please go to your magento customer account  and add more addresses).

Choose in hyvä checkout one of your addresses and click the edit button.

Then choose another address and click on the edti button.

You will recognise that not the correct address is shown for editing - it is shown the old one.

**Comment by schmengler** [comment]
An alternative solution can be to remove the header in checkout like it is done in the Luma checkout.

@wigman let's discuss it first. It may also be a simple event dispatch to update Hyvä Themes sections

**Comment by progammer-rkt** [comment]
Related pull request: https://github.com/hyva-themes/magento2-hyva-checkout/pull/81
