### ISSUE TITLE
Place order does not submit email address

### ISSUE THREAD

**Issue by wigman** [hyva-themes/magento2-hyva-checkout#75]
If you don't explicitly save the email address, order placement goes through (since the form is valid), but returns an error that the guest email is not set.

The email address should thus be saved when order is placed.

**Comment by wigman** [comment]
Also, no errors are shown.

**Comment by progammer-rkt** [comment]
@wigman This issue mentioned by @schmengler  and i guess we will be using https://github.com/hyva-themes/magento2-hyva-checkout/issues/53 for tracking it.

**Comment by progammer-rkt** [comment]
Fabian's comment is quoting below:

> I tested the validation on "Place order", that behavior is a bit irritating: the forms are considered valid when everything is entered, regardless if "update" has been clicked. so when I enter everything but for the email address forget to click "update", I get no validation message. I think the best would be to trigger the "update" actions of all changed forms when clicking "place order". maybe in that order:
> - validate
> - if valid and unsaved, trigger "update"
> - actual place order

**Comment by wigman** [comment]
Okay, sorry, missed that
