### ISSUE TITLE
csso-cli not included in package.json

### ISSUE THREAD

**Issue by DanielRuf** [hyva-themes/magento2-hyva-checkout#76]
In reactapp (I miss some documentation how to change things there and then compile) the `npx csso` command fails.

![grafik](https://user-images.githubusercontent.com/827205/122892182-77243d80-d345-11eb-9057-2ba1d920d3b6.png)

In general csso-cli is only installed in view/frontend/web/css/tailwind but not generally available.

Is there a clear documentation for the needed commands to make changes and recompile?
After running `npm i -g csso-cli` the `npm run build` command works.

**Comment by progammer-rkt** [comment]
Hi @DanielRuf , Thanks for reporting the issue.

You can find the detailed documentation here: https://hyva-themes.github.io/magento2-hyva-checkout/build/

`csso` is a global dependency as of now. We will be thinking to use this dependency locally or come up with some other elegant solution.

For now, please use the doc provided to build your app.

cc @wigman

**Comment by wigman** [comment]
I had already added csso-cli in the dev-dependencies locally, I'll push that along with the next PR.

**Comment by progammer-rkt** [comment]
@DanielRuf `csso-cli` is now included and locally referred to in the commands. So this package is no longer a global requirement now. Hence, closing this thread.
