### ISSUE TITLE
height attributes are problematic (buttons and more)

### ISSUE THREAD

**Issue by DanielRuf** [hyva-themes/magento2-hyva-checkout#79]
The button seems to need some more work (at least the line break and the button size do not match):

![grafik](https://user-images.githubusercontent.com/827205/122899198-e69d2b80-d34b-11eb-82c6-cdb819ad409d.png)

Seems to be caused by the height setting (not sure why a button with text needs a fixed height):

![grafik](https://user-images.githubusercontent.com/827205/122899320-03d1fa00-d34c-11eb-834e-0baa9042ec32.png)

![grafik](https://user-images.githubusercontent.com/827205/122899415-19dfba80-d34c-11eb-8275-6def1746d064.png)

Same for the div around the button component:

![grafik](https://user-images.githubusercontent.com/827205/122899861-7d69e800-d34c-11eb-8b81-e4c466c4921a.png)

Without `h-24` and `h-12` it still looks fine.

![grafik](https://user-images.githubusercontent.com/827205/122900441-fcf7b700-d34c-11eb-923a-12eb3439e57d.png)

Buttons and elements should not have fixed heights, as this can cause more problems on mobile views and like in this case (text can be of different lengths depending of the used language). Even min-height instead of height would make more sense (but would be problematic on smaller viewports when the text has enough space for just one line - so better to remove the heights).

**Comment by progammer-rkt** [comment]
Looking forward to a pull request, if you can please.

This is developed by a backend developer. Hence excuse the mistakes there in the styles. We will really appreciate correcting such style problems.

**Comment by progammer-rkt** [comment]
@wigman I think you resolved this. Can you please confirm?

**Comment by wigman** [comment]
Yes I'm removing these wherever I encounter them.
