### ISSUE TITLE
Inconsistent and outdated php code

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#98]
in the develop branch PHP code:

1. There are comments instead of property type declarations (php 7.4). Which version of php does the checkout support and would it be possible to switch to type declarations?
```php
    /**
     * @var StoreManagerInterface $storeManager
     */
    private $storeManager;

// versus

    private StoreManagerInterface $storeManager;
```
2. Some comments are incomplete, like this constructor. Some @throws statements are also missing.
```php
/**
     * CheckoutConfigProvider constructor.
     *
     * @param SerializerInterface $serializer
     * @param LocaleResolverInterface $localeResolver
     * @param CompositeConfigProvider $compositeConfigProvider
     */
    public function __construct(
        SerializerInterface $serializer,
        LocaleResolverInterface $localeResolver,
        CompositeConfigProvider $compositeConfigProvider,
        CurrencyProvider $currencyProvider // missing from comment
    ) {
```
3. Unnecessary qualifiers in comments
```php
use Magento\Framework\ObjectManagerInterface;

class JsonFactory extends \Magento\Framework\Controller\Result\JsonFactory
    /**
     * Providing a custom Json instance here.
     *
-     * @param  \Magento\Framework\ObjectManagerInterface  $objectManager
+     * @param ObjectManagerInterface  $objectManager
     * @param  string  $instanceName
     */
```
4. Suppression of code quality tool warnings, is there a good reason for this?
```php
    /**
     * @param CountryInformationAcquirer $subject
     * @param CountryInformation $result
     * @param string $countryId
     * @return CountryInformation
     *
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function afterGetCountryInfo(
        CountryInformationAcquirer $subject, // this is param is never used
        CountryInformation $result,
        string $countryId
    ): CountryInformation
```
5. Missing return type declaration (most have this, but some odd exceptions do not)
```php
private function getStore()
{
```
6. An undefined class being imported and used in Plugin/CustomerController/AjaxLogin.php  
Is this whole file deprecated? Should it still be in the repo?
```php
use Hyva\Checkout\Model\LoginSectionDataServiceFactory;
```
7. Usage of deprecated magento function isOutputEnabled
```php
    /**
     * Whether a module output is permitted by the configuration or not
     *
     * @param string $moduleName Fully-qualified module name
     * @return boolean
     * @deprecated 101.0.0 Magento does not support disabling/enabling modules output from the Admin Panel since 2.2.0
     * version. Module output can still be enabled/disabled in configuration files. However, this functionality should
     * not be used in future development. Module design should explicitly state dependencies to avoid requiring output
     * disabling. This functionality will temporarily be kept in Magento core, as there are unresolved modularity
     * issues that will be addressed in future releases.
     */
    public function isOutputEnabled($moduleName)
```

**Comment by schmengler** [comment]
Thanks for your review!

> There are comments instead of property type declarations (php 7.4). Which version of php does the checkout support and would it be possible to switch to type declarations?

This is intentionally to match current system requirements of Hyvä (PHP 7.3+). They shall be converted to type declarations when this is dropped in some near future.

> Some comments are incomplete, like this constructor. Some `@throws` statements are also missing.

This comment is even completely redundant :grin: 

> Suppression of code quality tool warnings, is there a good reason for this?

Yes, usually there should be an explaining comment but this one is so common that it seems unnecessary. Magento plugins need a specific signature but sometimes you don't need to do anything with the subject, just with the arguments and/or return value.

> Unnecessary qualifiers in comments

> Missing return type declaration (most have this, but some odd exceptions do not)

Sure, that can be improved, if you want to create a PR, I'd merge it immediately :+1: 

> An undefined class being imported and used in Plugin/CustomerController/AjaxLogin.php
Is this whole file deprecated? Should it still be in the repo?

This class is automatically generated by the Magento framework: https://devdocs.magento.com/guides/v2.4/extension-dev-guide/code-generation.html

> Usage of deprecated magento function isOutputEnabled
Good point. @progammer-rkt I think we can drop that check and rely on module configuration only

**Comment by progammer-rkt** [comment]
@peterschriever 
> 3. Unnecessary qualifiers in comments
This is already fixed in the `develop` branch. Are you using an older version of develop?

**Comment by progammer-rkt** [comment]
The relevant issues in this thread are now reached `develop` branch. Hence, closing this issue.
